refactor: dm-report merged to dm-check, naming

diff --git a/bin/daimon b/bin/daimon
--- a/bin/daimon
+++ b/bin/daimon
@@ -7,21 +7,20 @@ function helpme {
 	then
 		echo -e "$1" 1>&2
 	else
-		grep '#' /proc/$$/fd/255 | sed -n '/^#HELPME_START/,/^#HELPME_END/p' | grep -v "^#HELPME_" | sed -e "s/#//" | tr -s '\t' 1>&2 #20220313
+		grep '#' /proc/$$/fd/255 | sed -n '/^#HELPME_START/,/^#HELPME_END/p' | grep -v "^#HELPME_" | sed -e "s/#//" | tr -s '\t' 1>&2 #20220605
 	fi
-	PGID=$(cut -d ' ' -f 5 /proc/$$/stat)
-	kill -s TERM -- -$PGID
+	kill -s TERM -- -$(cut -d ' ' -f 5 /proc/$$/stat)
 }
-CONFIG=/etc/daimon.conf
-. $CONFIG || helpme "ERR-100: Configuration file $CONFIG is missing"
-EMAIL=""
-TASK=""
-let COUNT=1
-let TIMEOUT=60
-OPT_SHORT="hvt:m:n:s:"
-OPT_LONG="help,version,task:,mail:,count:,seconds:"
-OPTS=$(getopt -o $OPT_SHORT --long $OPT_LONG -n "$(basename $0)" -- "$@")
-eval set -- "$OPTS"
+DaimonConf=/etc/daimon.conf
+. $DaimonConf || helpme "ERR-100: Configuration file $DaimonConf is missing"
+EmailTo=""
+Task=""
+let Count=1
+let Timeout=60
+OptShort="hvt:m:n:s:"
+OptLong="help,version,task:,mail:,count:,seconds:"
+Opts=$(getopt -o $OptShort --long $OptLong -n "$(basename $0)" -- "$@")
+eval set -- "$Opts"
 while [ $# -gt 0 ]
 do
 	case "$1" in
@@ -38,17 +37,17 @@ do
 		-v )	#verbose output
 			set -x
 			shift ;;
-		-t | --task)	#name of a sub-directory under $DAIMON_HOME/var
-			TASK=$2
+		-t | --task)	#name of a sub-directory under $DaimonHome/var
+			Task=$2
 			shift 2 ;;
 		-m | --mail)	#email addresses the alerts will be sent to, seperated by comma
-			EMAIL=$(echo $2 | sed -e "s/,/ /g")
+			EmailTo=$(echo $2 | sed -e "s/,/ /g")
 			shift 2 ;;
-		-n | --count)	#send up to COUNT alerts for a new incident, default 1
-			let COUNT=$2 || helpme "ERR-101: -n needs a positive number"
+		-n | --count)	#send up to Count alerts for a new incident, default 1
+			let Count=$2 || helpme "ERR-101: -n needs a positive number"
 			shift 2 ;;
 		-s | --seconds)	#timeout of CMD, in seconds, default 60
-			let TIMEOUT=$2 || helpme "ERR-107: -s needs a positive number"
+			let Timeout=$2 || helpme "ERR-107: -s needs a positive number"
 			shift 2 ;;
 		--)
 			shift 1 ;;
@@ -64,104 +63,104 @@ do
 #HELPME_END
 	esac
 done
-if [ "$DAIMON_EMAIL" != "NO" ]
+if [ "$DaimonEmail" != "NO" ]
 then
 	set +u
-	[ -n "$EMAIL" ] || EMAIL=$MAILTO
-	[ -n "$EMAIL" ] || EMAIL=$USER
+	[ -n "$EmailTo" ] || EmailTo=$MAILTO
+	[ -n "$EmailTo" ] || EmailTo=$USER
 	set -u
-	[ -n "$EMAIL" ] || helpme "ERR-102: -m needs an email address"
+	[ -n "$EmailTo" ] || helpme "ERR-102: -m needs an email address"
 fi
-CMD="$@"
-[ -n "$DAIMON_HOME" ] || helpme "ERR-103: missing environment variable DAIMON_HOME in Configuration file $CONFIG"
-[ -d "$DAIMON_HOME" ] || helpme "ERR-104: $DAIMON_HOME is not a directory"
-[ -n "$TASK" ] || helpme "ERR-105: TASK is missing"
-ID=$DAIMON_HOME/var/$TASK
+Cmd="$@"
+[ -n "$DaimonHome" ] || helpme "ERR-103: missing environment variable DaimonHome in Configuration file $DaimonConf"
+[ -d "$DaimonHome" ] || helpme "ERR-104: $DaimonHome is not a directory"
+[ -n "$Task" ] || helpme "ERR-105: Task is missing"
+Dir=$DaimonHome/var/$Task
 [ -t 1 ] || sleep $[ $RANDOM%10 ]
-if [ ! -f $ID/out-standard ]
+if [ ! -f $Dir/out-standard ]
 then
-	mkdir -p $ID
-	rm -f $ID/diff-count
-	if ! timeout $TIMEOUT bash -c "$CMD" &> $ID/out-current
+	mkdir -p $Dir
+	rm -f $Dir/diff-count
+	if ! timeout $Timeout bash -c "$Cmd" &> $Dir/out-current
 	then 
-		cat $ID/out-current
-		echo 99999 > $ID/diff-count
-		helpme "ERR-106: INITIALIZING FAILED FOR $TASK"
+		cat $Dir/out-current
+		echo 99999 > $Dir/diff-count
+		helpme "ERR-106: Initialization failed for $Task"
 	fi
-	mv $ID/out-current $ID/out-standard
-	cat $ID/out-standard 
-	[ "$DAIMON_EMAIL" = "NO" ] || cat $ID/out-standard | mail -s "$TASK is initalized successfully. If the command output is not right, let admins know it" $EMAIL
+	mv $Dir/out-current $Dir/out-standard
+	cat $Dir/out-standard 
+	[ "$DaimonEmail" = "NO" ] || cat $Dir/out-standard | mail -s "$Task is initalized successfully. If the command output is not right, let admins know it" $EmailTo
 else
-	if fuser $ID/lock &> /dev/null
+	if fuser $Dir/lock &> /dev/null
 	then
-		fuser -k $ID/lock &> /dev/null
-		echo "ERR-002: A previous $TASK is killed as it is stuck" > $ID/out-current
+		fuser -k $Dir/lock &> /dev/null
+		echo "ERR-002: A previous $Task is killed as it is stuck" > $Dir/out-current
 	else
-		rm -f $ID/out-current
+		rm -f $Dir/out-current
 	fi
 	(
 		if ! flock -xn 99
 		then
-			echo "$TASK ERR-001: flock failed"
-			[ "$DAIMON_EMAIL" = "NO" ] || echo | mail -s "$TASK ERR-001: flock failed" $EMAIL
+			echo "$Task ERR-001: flock failed"
+			[ "$DaimonEmail" = "NO" ] || echo | mail -s "$Task ERR-001: flock failed" $EmailTo
 			exit
 		fi
 		set +e
-		timeout $TIMEOUT bash -c "$CMD" >> $ID/out-current 2>> $ID/out-current
-		let RTN=$?
+		timeout $Timeout bash -c "$Cmd" >> $Dir/out-current 2>> $Dir/out-current
+		let Rtn=$?
 		set -e
-		if [ $RTN -eq 124 -o $RTN -eq 125 -o $RTN -eq 126 -o $RTN -eq 127 -o $RTN -eq 137 ]
+		if [ $Rtn -eq 124 -o $Rtn -eq 125 -o $Rtn -eq 126 -o $Rtn -eq 127 -o $Rtn -eq 137 ]
 		then
-			echo "timeout returned $RTN" >> $ID/out-current
-		elif [ $RTN -ne 0 ]
+			echo "timeout returned $Rtn" >> $Dir/out-current
+		elif [ $Rtn -ne 0 ]
 		then
-			echo "sub-command returned $RTN" >> $ID/out-current
+			echo "sub-command returned $Rtn" >> $Dir/out-current
 		fi
 		set +f
-		for STD in $(cd $ID && ls out-standard.* 2>/dev/null) out-standard
+		for Standard in $(cd $Dir && ls out-standard.* 2>/dev/null) out-standard
 		do
-			if diff $ID/out-current $ID/$STD > $ID/diff-$STD 2> /dev/null
+			if diff $Dir/out-current $Dir/$Standard > $Dir/diff-$Standard 2> /dev/null
 			then
 				break
 			fi
 		done
-		cd $ID && mv $(ls -rS diff-out-standard* | head -n 1) diff-current && rm -f diff-out-standard* 2> /dev/null
+		cd $Dir && mv $(ls -rS diff-out-standard* | head -n 1) diff-current && rm -f diff-out-standard* 2> /dev/null
 		set -f
-		if [ -f $ID/diff-count ]
+		if [ -f $Dir/diff-count ]
 		then
-			let FAILED_PRV=$(cat $ID/diff-count) || :
+			let FailedCntPrv=$(cat $Dir/diff-count) || :
 		else
-			let FAILED_PRV=0 || :
+			let FailedCntPrv=0 || :
 		fi
-		if [ -s $ID/diff-current ]
+		if [ -s $Dir/diff-current ]
 		then
-			if [ $FAILED_PRV -gt 0 ] && diff -q $ID/diff-current $ID/diff-previous &> /dev/null
+			if [ $FailedCntPrv -gt 0 ] && diff -q $Dir/diff-current $Dir/diff-previous &> /dev/null
 			then
-				let FAILED_CUR=$FAILED_PRV+1
+				let FailedCountCur=$FailedCntPrv+1
 			else
-				let FAILED_CUR=1
-				cp $ID/diff-current $ID/diff-previous
-				cp $ID/diff-current $ID/history-$(date +%FT%T)-abnm
+				let FailedCountCur=1
+				cp $Dir/diff-current $Dir/diff-previous
+				cp $Dir/diff-current $Dir/history-$(date +%FT%T)-abnm
 			fi
-			echo $FAILED_CUR > $ID/diff-count
-			if [ $FAILED_CUR -le $COUNT ]
+			echo $FailedCountCur > $Dir/diff-count
+			if [ $FailedCountCur -le $Count ]
 			then
-				if [ $FAILED_CUR -eq $COUNT -a $COUNT -gt 1 ]
+				if [ $FailedCountCur -eq $Count -a $Count -gt 1 ]
 				then
-					SUBJECT="$TASK is detected (FINAL ALERT)"
+					SUBJECT="$Task is detected (FINAL ALERT)"
 				else
-					SUBJECT="$TASK is detected"
+					SUBJECT="$Task is detected"
 				fi
-				[ "$DAIMON_EMAIL" = "NO" ] || cat $ID/diff-current | strings -n 1 2>&1 | mail -s "$SUBJECT" $EMAIL
+				[ "$DaimonEmail" = "NO" ] || cat $Dir/diff-current | strings -n 1 2>&1 | mail -s "$SUBJECT" $EmailTo
 			fi
 		else
-			if [ $FAILED_PRV -gt 0 ]
+			if [ $FailedCntPrv -gt 0 ]
 			then
-				[ "$DAIMON_EMAIL" = "NO" ] || cat $ID/out-current | strings -n 1 2>&1 | mail -s "$TASK is back to normal" $EMAIL
-				echo $FAILED_PRV > $ID/history-$(date +%FT%T)-norm
+				[ "$DaimonEmail" = "NO" ] || cat $Dir/out-current | strings -n 1 2>&1 | mail -s "$Task is back to normal" $EmailTo
+				echo $FailedCntPrv > $Dir/history-$(date +%FT%T)-norm
 			fi
-			echo 0 > $ID/diff-count
-			rm -f $ID/diff-previous
+			echo 0 > $Dir/diff-count
+			rm -f $Dir/diff-previous
 		fi
-	) 99> $ID/lock
+	) 99> $Dir/lock
 fi
diff --git a/bin/dm-ssh b/bin/dm-ssh
--- a/bin/dm-ssh
+++ b/bin/dm-ssh
@@ -4,7 +4,7 @@ set -o pipefail
 trap "exit 1" TERM
 function cleanme {
 	set +u
-	[ -z "$JOB" ] || rm -f $JOB $JOB-set $JOB-exclude $JOB-host-* $JOB-nodes
+	[ -z "$Job" ] || rm -f $Job $Job-set $Job-exclude $Job-host-* $Job-nodes
 	set -u
 }
 function message {
@@ -18,30 +18,28 @@ function helpme {
 	then
 		echo -e "$1" 1>&2
 	else
-		grep '#' /proc/$$/fd/255 | sed -n '/^#HELPME_START/,/^#HELPME_END/p' | grep -v "^#HELPME_" | sed -e "s/#//" | tr -s '\t' 1>&2 #20220313
+		grep '#' /proc/$$/fd/255 | sed -n '/^#HELPME_START/,/^#HELPME_END/p' | grep -v "^#HELPME_" | sed -e "s/#//" | tr -s '\t' 1>&2 #20220605
 	fi
-	PGID=$(cut -d ' ' -f 5 /proc/$$/stat)
-	kill -s TERM -- -$PGID
+	kill -s TERM -- -$(cut -d ' ' -f 5 /proc/$$/stat)
 }
-CONF=~/.dm-ssh.conf
-if [ ! -f $CONF ]
+DmsshConf=~/.dm-ssh.conf
+if [ ! -f $DmsshConf ]
 then
-	CONF=/etc/dm-ssh.conf
-	[ -f $CONF ] || helpme "ERR-001: missing config file ~/.dm-ssh.conf or /etc/dm-ssh.conf"
+	DmsshConf=/etc/dm-ssh.conf
+	[ -f $DmsshConf ] || helpme "ERR-001: missing config file ~/.dm-ssh.conf or /etc/dm-ssh.conf"
 fi
-LIST=NO
-DELAY=0
-ARGLIST=$@
-OPT_SHORT="hvlu:s:e:E:H:j:d:"
-OPT_LONG="help,version,list,user:set:,exclude-hosts:,exclude-sets:,header:,jobs:delay:"
-OPTS=$(getopt -o $OPT_SHORT --long $OPT_LONG -n dm-ssh -- "$@")
-HEADER=0
-SSHUSER=$USER
-JOB=$(mktemp /tmp/dm-ssh-XXXX )
-[ -n "$JOB" ] || helpme "ERR-007: failed to create temp file"
-PARALLEL=0
-echo -n > $JOB-exclude
-eval set -- "$OPTS"
+List=NO
+Delay=0
+OptShort="hvlu:s:e:E:H:j:d:"
+OptLong="help,version,list,user:set:,exclude-hosts:,exclude-sets:,header:,jobs:delay:"
+Opts=$(getopt -o $OptShort --long $OptLong -n dm-ssh -- "$@")
+HeaderLines=0
+SshUser=$USER
+Job=$(mktemp /tmp/dm-ssh-XXXX )
+[ -n "$Job" ] || helpme "ERR-007: failed to create temp file"
+Parallel=0
+echo -n > $Job-exclude
+eval set -- "$Opts"
 while [ $# -gt 0 ]
 do
 	case "$1" in
@@ -64,32 +62,32 @@ do
 			set -x
 			shift ;;
 		-l | --list)	#list all sets and their hosts
-			LIST=YES
+			List=YES
 			shift ;;
 		-u | --user)	#user name used to connect to the nodes
-			SSHUSER=$2
+			SshUser=$2
 			shift 2 ;;
 		-s | --set)	#host set name defined in output of '-l'
-			SET=$2
+			Set=$2
 			shift 2 ;;
 		-e | --exclude-hosts)	#exclude hosts. E.g. host-1,host-2
-			echo $2 | sed -e "s/,/\n/g" >> $JOB-exclude
+			echo $2 | sed -e "s/,/\n/g" >> $Job-exclude
 			shift 2 ;;
 		-E | --exclude-sets)	#excluded host sets. E.g. set1,set2
 			echo $2 | sed -e "s/,/\n/g" | while read E
 			do
-				grep -q ^$E: $CONF || helpme "ERR-006: exclude-set '$E' doesn't exist"
-				grep ^$E: $CONF | cut -d '	' -f 2 |sed -e "s/,/\n/g" >> $JOB-exclude
+				grep -q ^$E: $DmsshConf || helpme "ERR-006: exclude-set '$E' doesn't exist"
+				grep ^$E: $DmsshConf | cut -d '	' -f 2 |sed -e "s/,/\n/g" >> $Job-exclude
 			done
 			shift 2 ;;
 		-H | --header)	#number of header lines
-			((HEADER=$2))
+			((HeaderLines=$2))
 			shift 2 ;;
 		-j | --jobs)	#number of parallel jobs, default 0 means as many as possible
-			PARALLEL=$2
+			Parallel=$2
 			shift 2 ;;
 		-d | --delay)	#NUM, sleep a random fraction of NUM seconds before ssh-ing, default 0
-			((DELAY=$2))
+			((Delay=$2))
 			shift 2 ;;
 		--)
 			shift 1 
@@ -106,21 +104,21 @@ do
 #HELPME_END
 	esac
 done
-if [ "$LIST" = "YES" ]
+if [ "$List" = "YES" ]
 then
-	cat $CONF
+	cat $DmsshConf
 	cleanme
 	exit
 fi
-CMD="$*"
+Cmd="$*"
 [ $# -gt 0 ] || helpme "ERR-002: use -h/--help"
-[ -n "$SET" ] || helpme "ERR-003: parameter -s is missing"
+[ -n "$Set" ] || helpme "ERR-003: parameter -s is missing"
 which parallel &> /dev/null || helpme "ERR-004: missing command 'parallel'"
 set +e
-if [ "$SET" != "all" -a "$(join -v 2 <(grep ^$SET: $CONF | cut -d '	' -f 2 |sed -e "s/,/\n/g" |sort -u ) <(sort -u $JOB-exclude) | wc -l )" != "0" ]
+if [ "$Set" != "all" -a "$(join -v 2 <(grep ^$Set: $DmsshConf | cut -d '	' -f 2 |sed -e "s/,/\n/g" |sort -u ) <(sort -u $Job-exclude) | wc -l )" != "0" ]
 then
-	join -v 2 <(grep ^$SET: $CONF | cut -d '	' -f 2 |sed -e "s/,/\n/g" |sort -u ) <(sort -u $JOB-exclude)
-	read -n 1 -r -p "The nodes above are excluded, but they are not in the node set \"$SET\", you might want to fix your -e/E. continue? [y/N]" yn
+	join -v 2 <(grep ^$Set: $DmsshConf | cut -d '	' -f 2 |sed -e "s/,/\n/g" |sort -u ) <(sort -u $Job-exclude)
+	read -n 1 -r -p "The nodes above are excluded, but they are not in the node set \"$Set\", you might want to fix your -e/E. continue? [y/N]" yn
 	case "$yn" in
 		Y|y )
 			echo
@@ -133,65 +131,65 @@ then
 			helpme "Please answer y or n!"
 	esac
 fi
-if [ "$SET" = "all" ]
+if [ "$Set" = "all" ]
 then
-	! grep -q "^all:" $CONF || helpme "ERR-008: 'all' is a reserved set name"
-	cat $CONF > $JOB-set
-elif grep -q ^$SET: $CONF
+	! grep -q "^all:" $DmsshConf || helpme "ERR-008: 'all' is a reserved set name"
+	cat $DmsshConf > $Job-set
+elif grep -q ^$Set: $DmsshConf
 then
-	grep ^$SET: $CONF > $JOB-set
+	grep ^$Set: $DmsshConf > $Job-set
 else
 	helpme "ERR-005: such set doesn't exist"
 fi
-join -v 1 <( cut -d '	' -f 2 $JOB-set | sed -e "s/,/\n/g" | sort -u ) <(sort -u $JOB-exclude) > $JOB-nodes
+join -v 1 <( cut -d '	' -f 2 $Job-set | sed -e "s/,/\n/g" | sort -u ) <(sort -u $Job-exclude) > $Job-nodes
 message "####ssh to####"
-echo -ne "..$(head -n 1 $JOB-nodes)\r" 1>&2
-paste <(cat $JOB-nodes) <(tail -n +2 $JOB-nodes; echo DONE ) |parallel -k -j $PARALLEL --colsep '\t' "
-	sleep \$(bc <<< \"scale=3; $DELAY*\$RANDOM/32768\" );
-	ssh -o ConnectTimeout=2 -o LogLevel=error -o StrictHostKeyChecking=no -n $SSHUSER@{1} \"$CMD\" &> $JOB-host-{1};
-	RTN=\$?;
-	echo -n -e \"\$RTN:{1} \n..{2}\r\" 1>&2;
-	[ \"\$(tail -c 1 $JOB-host-{1} | od -iAn | tr -d ' ' )\" != \"10\" ] && echo -e \"\n\" >> $JOB-host-{1};
-	echo \$RTN >> $JOB-host-{1};
+echo -ne "..$(head -n 1 $Job-nodes)\r" 1>&2
+paste <(cat $Job-nodes) <(tail -n +2 $Job-nodes; echo DONE ) |parallel -k -j $Parallel --colsep '\t' "
+	sleep \$(bc <<< \"scale=3; $Delay*\$RANDOM/32768\" );
+	ssh -o ConnectTimeout=2 -o LogLevel=error -o StrictHostKeyChecking=no -n $SshUser@{1} \"$Cmd\" &> $Job-host-{1};
+	Rtn=\$?;
+	echo -n -e \"\$Rtn:{1} \n..{2}\r\" 1>&2;
+	[ \"\$(tail -c 1 $Job-host-{1} | od -iAn | tr -d ' ' )\" != \"10\" ] && echo -e \"\n\" >> $Job-host-{1};
+	echo \$Rtn >> $Job-host-{1};
 "
 message "####Output####"
 [ ! -t 1 ] || tabs 16
-FAILEDHOSTS=()
-HEADER_PRINTED=NO
+FailedHosts=()
+HeaderPrinted=NO
 re='^[0-9]+$'
-for ((CMP=0; CMP<2; CMP++))
+for ((Cmp=0; Cmp<2; Cmp++))
 do
 	set +f
-	for F in $JOB-host-*
+	for F in $Job-host-*
 	do
-		RTN=$(tail -n 1 $F)
-		if [ -z "$RTN" ]
+		Rtn=$(tail -n 1 $F)
+		if [ -z "$Rtn" ]
 		then
-			let RTN=1
-		elif [[ $RTN =~ $re ]]
+			let Rtn=1
+		elif [[ $Rtn =~ $re ]]
 		then
-			let RTN=$RTN
+			let Rtn=$Rtn
 		else
-			let RTN=1
+			let Rtn=1
 		fi
-		if [[ ( $RTN = 0 && $CMP = 0 ) || ( $RTN != 0 && $CMP != 0 ) ]]
+		if [[ ( $Rtn = 0 && $Cmp = 0 ) || ( $Rtn != 0 && $Cmp != 0 ) ]]
 		then
-			if [ "$HEADER_PRINTED" = "NO" -a $RTN -eq 0 ]
+			if [ "$HeaderPrinted" = "NO" -a $Rtn -eq 0 ]
 			then
-				HEADER_PRINTED=YES
-				head -n $HEADER $F | sed -e "s/^/HEADER:\t/"
-				((HEADER++))
+				HeaderPrinted=YES
+				head -n $HeaderLines $F | sed -e "s/^/HeaderLines:\t/"
+				((HeaderLines++))
 			fi
-			HOST="$(echo $F | sed -e 's/.*-host-//' )"
-			tail -n +$HEADER $F | head -n -1 | sed -e "s/^/$RTN:$HOST:\t/"
-		elif [ $CMP -eq 0 ]
+			Host="$(echo $F | sed -e 's/.*-host-//' )"
+			tail -n +$HeaderLines $F | head -n -1 | sed -e "s/^/$Rtn:$Host:\t/"
+		elif [ $Cmp -eq 0 ]
 		then
-			FAILEDHOSTS+=( $( basename $F |cut -d - -f 5-))
+			FailedHosts+=( $( basename $F |cut -d - -f 5-))
 		fi
 	done
 	set -f
 done
 cleanme
-[ ${#FAILEDHOSTS[@]} -gt 0 ] && message "\n####Failed hosts: ${#FAILEDHOSTS[@]}" && echo "${FAILEDHOSTS[*]}"
+[ ${#FailedHosts[@]} -gt 0 ] && message "\n####Failed hosts: ${#FailedHosts[@]}" && echo "${FailedHosts[*]}"
 [ ! -t 1 ] || tabs 8
-[ ${#FAILEDHOSTS[@]} -eq 0 ]
+[ ${#FailedHosts[@]} -eq 0 ]
