Feat! dm-ssh more like ssh; detects common lines

diff --git a/bin/dm-ssh b/bin/dm-ssh
--- a/bin/dm-ssh
+++ b/bin/dm-ssh
@@ -3,13 +3,13 @@ set -Eeufo pipefail
 trap "exit 1" TERM
 function cleanme {
 	set +u
-	[ -z "$Job" ] || rm -f $Job $Job-set $Job-exclude $Job-host-* $Job-nodes
+	[ -z "$Job" ] ||rm -f $Job $Job-set $Job-exclude $Job-host-* $Job-nodes
 	set -u
 }
 function message {
-	[ ! -t 1 ] || tput setaf 1
+	[ ! -t 1 ] ||tput setaf 1
 	echo -e $1
-	[ ! -t 1 ] || tput sgr0
+	[ ! -t 1 ] ||tput sgr0
 }
 function helpme {
 	cleanme
@@ -17,7 +17,11 @@ function helpme {
 	then
 		echo -e "$1" 1>&2
 	else
-		grep '#' /proc/$$/fd/255 | sed -n '/^#HELPME_START/,/^#HELPME_END/p' | grep -v "^#HELPME_" | sed -e "s/#//" | tr -s '\t' 1>&2 #20220605
+		grep '#' /proc/$$/fd/255 |
+			sed -n '/^#HELPME_START/,/^#HELPME_END/p' |
+			grep -v "^#HELPME_" |
+			sed "s/#//" |
+			tr -s '\t' 1>&2
 	fi
 	kill -s TERM -- -$(cut -d ' ' -f 5 /proc/$$/stat)
 }
@@ -25,20 +29,18 @@ DmsshConf=~/.dm-ssh.conf
 if [ ! -f $DmsshConf ]
 then
 	DmsshConf=/etc/dm-ssh.conf
-	[ -f $DmsshConf ] || helpme "ERR-001: missing config file ~/.dm-ssh.conf or /etc/dm-ssh.conf"
+	[ -f $DmsshConf ] ||
+		helpme "ERR-001: missing config file ~/.dm-ssh.conf or /etc/dm-ssh.conf"
 fi
-List=NO
 Delay=0
 Timeout=2
-OptShort="hvlu:s:n:e:E:H:j:d:t:"
-OptLong="help,version,list,user:set:,include-hosts:,exclude-hosts:,exclude-sets:,header:,jobs:delay:timeout:"
+Quiet=No
+OptShort="hvln:e:E:H:j:d:t:q"
+OptLong="help,version,list,include-hosts:,exclude-hosts:,exclude-sets:,header:,jobs:delay:,timeout:,quiet"
 Opts=$(getopt -o $OptShort --long $OptLong -n dm-ssh -- "$@")
-HeaderLines=0
-SshUser=$USER
 Job=$(mktemp /tmp/dm-ssh-XXXX )
-[ -n "$Job" ] || helpme "ERR-007: failed to create temp file"
+[ -n "$Job" ] ||helpme "ERR-007: failed to create temp file"
 Parallel=0
-Set=""
 IncludeHosts=""
 echo -n > $Job-exclude
 eval set -- "$Opts"
@@ -51,52 +53,48 @@ do
 #SYNOPSIS
 #	dm-ssh [OPTION]...
 #EXAMPLE
-#	echo -e "set1:\tlocalhost\nset2:\tlocalhost,$HOSTNAME" | tee ~/.dm-ssh.conf #define two host sets
+#	echo -e "set1:\tlocalhost\nset2:\tlocalhost,$HOSTNAME" |tee ~/.dm-ssh.conf #define two host sets
 #	dm-ssh -h
-#	dm-ssh -s set1 -- hostname
-#	dm-ssh -s set2 -H 1 -- df -lh
+#	dm-ssh set1 -- hostname
+#	dm-ssh root@set2 -- df -lh
 #DESCRIPTION
-		-h | --help)	#print help information
+		-h |--help)	#print help information
 			helpme ;;
 		--version)	#print version
-			helpme 20230720 ;;
+			helpme 20231118 ;;
 		-v )	#verbose output
 			set -x
 			shift ;;
-		-l | --list)	#list all sets and their hosts
-			List=YES
-			shift ;;
-		-u | --user)	#user name used to connect to the hosts
-			SshUser=$2
-			shift 2 ;;
-		-s | --set)	#host set name defined in output of '-l'
-			Set=$2
-			shift 2 ;;
-		-n | --include-hosts)	#a list of host name. E.g. host-1,host-2
+		-l |--list)	#list all sets and their hosts
+			cat $DmsshConf
+			message $DmsshConf
+			cleanme
+			exit ;;
+		-n |--include-hosts)	#a list of host name. E.g. host-1,host-2
 			IncludeHosts=$2
 			shift 2 ;;
-		-e | --exclude-hosts)	#exclude hosts. E.g. host-1,host-2
-			echo $2 | sed -e "s/,/\n/g" >> $Job-exclude
+		-e |--exclude-hosts)	#exclude hosts. E.g. host-1,host-2
+			echo $2 |sed "s/,/\n/g" >> $Job-exclude
 			shift 2 ;;
-		-E | --exclude-sets)	#excluded host sets. E.g. set1,set2
-			echo $2 | sed -e "s/,/\n/g" | while read E
+		-E |--exclude-sets)	#excluded host sets. E.g. set1,set2
+			echo $2 |sed "s/,/\n/g" |while read E
 			do
-				grep -q ^$E: $DmsshConf || helpme "ERR-006: exclude-set '$E' doesn't exist"
-				grep ^$E: $DmsshConf | cut -d '	' -f 2 |sed -e "s/,/\n/g" >> $Job-exclude
+				grep -q ^$E: $DmsshConf ||helpme "ERR-006: exclude-set '$E' doesn't exist"
+				grep ^$E: $DmsshConf |cut -d '	' -f 2 |sed "s/,/\n/g" >> $Job-exclude
 			done
 			shift 2 ;;
-		-H | --header)	#number of header lines
-			((HeaderLines=$2))
-			shift 2 ;;
-		-j | --jobs)	#number of parallel jobs, default 0 means as many as possible
+		-j |--jobs)	#number of parallel jobs, default 0 means as many as possible
 			Parallel=$2
 			shift 2 ;;
-		-d | --delay)	#NUM, sleep a random fraction of NUM seconds before ssh-ing, default 0
+		-d |--delay)	#NUM, sleep a random fraction of NUM seconds before ssh-ing, default 0
 			((Delay=$2))
 			shift 2 ;;
-		-t | --timeout)	#SECONDS, ConnectTimeout in ssh, default 2
+		-t |--timeout)	#SECONDS, ConnectTimeout in ssh, default 2
 			((Timeout=$2))
 			shift 2 ;;
+		-q |--quiet)	#quiet
+			Quiet=Yes
+			shift ;;
 		--)
 			shift 1
 			break ;;
@@ -109,85 +107,96 @@ do
 #HELPME_END
 	esac
 done
-if [ "$List" = "YES" ]
-then
-	cat $DmsshConf
-	cleanme
-	exit
-fi
-Cmd="$*"
-[ $# -gt 0 ] || helpme "ERR-002: use -h/--help"
-which parallel &> /dev/null || helpme "ERR-004: missing command 'parallel'"
+which parallel &> /dev/null ||helpme "ERR-004: missing command 'parallel'"
+[ $# -gt 1 ] ||helpme "ERR-002: use -h/--help"
+Set=$1
+Arr=(${Set//@/ })
+case "${#Arr[@]}" in
+	1 )
+		SshUser=$USER ;;
+	2 )
+		SshUser=${Arr[0]}
+		Set=${Arr[1]} ;;
+	0 )
+		helpme "ERR-008: set name cannot be empty string";;
+	* )
+		helpme "ERR-009: set name can have up to one @";;
+esac
+shift
+Cmd="$@"
 rm -f $Job-set
-[ -z "$Set" ] || grep ^$Set: $DmsshConf >> $Job-set || helpme "ERR-005: such set doesn't exist"
-[ -z "$IncludeHosts" ] || echo "$IncludeHosts" >> $Job-set
-[ -s "$Job-set" ] || helpme "ERR-003: parameter -s or -n is missing"
+[ -z "$Set" ] ||grep ^$Set: $DmsshConf >> $Job-set ||helpme "ERR-005: such set doesn't exist"
+[ -z "$IncludeHosts" ] ||echo "$IncludeHosts" >> $Job-set
+[ -s "$Job-set" ] ||helpme "ERR-003: parameter -s or -n is missing"
 set +e
-if [ "$Set" != "all" -a "$(join -v 2 <( (grep ^$Set: $DmsshConf | cut -d '	' -f 2 && echo $IncludeHosts ) |sed -e "s/,/\n/g" |sort -u ) <(sort -u $Job-exclude) | wc -l )" != "0" ]
+if [ "$Set" != "all" -a "$(join -v 2 <( (grep ^$Set: $DmsshConf |cut -d '	' -f 2 && echo $IncludeHosts ) |sed "s/,/\n/g" |sort -u ) <(sort -u $Job-exclude) |wc -l )" != "0" ]
 then
-	join -v 2 <(grep ^$Set: $DmsshConf | cut -d '	' -f 2 |sed -e "s/,/\n/g" |sort -u ) <(sort -u $Job-exclude)
+	join -v 2 <(grep ^$Set: $DmsshConf |cut -d '	' -f 2 |sed "s/,/\n/g" |sort -u ) <(sort -u $Job-exclude)
 	read -n 1 -r -p "The hosts above are excluded, but they are not in the node set \"$Set\", you might want to fix your -e/E. continue? [y/N]" yn
 	case "$yn" in
 		Y|y )
-			echo
-			;;
+			echo ;;
 		N|n )
 			echo
 			cleanme
 			exit 1 ;;
 		* )
-			helpme "Please answer y or n!"
+			helpme "Please answer y or n!";;
 	esac
 fi
-join -v 1 <( cut -d '	' -f 2 $Job-set | sed -e "s/,/\n/g" | sort -u ) <(sort -u $Job-exclude) > $Job-nodes
-message "####ssh to####"
-echo -ne "..$(head -n 1 $Job-nodes)\r" 1>&2
+join -v 1 <( cut -d '	' -f 2 $Job-set |sed "s/,/\n/g" |sort -u ) <(sort -u $Job-exclude) > $Job-nodes
+if [ "$Quiet" != "Yes" ]
+then
+	message "####Ssh####"
+	echo -ne "..$(head -n 1 $Job-nodes)\r"
+fi
 paste <(cat $Job-nodes) <(tail -n +2 $Job-nodes; echo DONE ) |parallel -k -j $Parallel --colsep '\t' "
 	sleep \$(bc <<< \"scale=3; $Delay*\$RANDOM/32768\" );
-	ssh -o ConnectTimeout=$Timeout -o LogLevel=error -o StrictHostKeyChecking=no -o BatchMode=yes -n $SshUser@{1} \"$Cmd\" &> $Job-host-{1};
+	ssh -o ControlMaster=auto -o ControlPath=~/.ssh/dm-ssh-%r%n-%p -o ControlPersist=60  -o ConnectTimeout=$Timeout -o LogLevel=error -o StrictHostKeyChecking=no -o BatchMode=yes -n $SshUser@{1} \"$Cmd\" &> $Job-host-{1};
 	Rtn=\$?;
-	echo -n -e \"\$Rtn:{1} \n..{2}\r\" 1>&2;
-	[ \"\$(tail -c 1 $Job-host-{1} | od -iAn | tr -d ' ' )\" != \"10\" ] && echo -e \"\n\" >> $Job-host-{1};
+	[ "$Quiet" = "Yes" ] ||echo -n -e \"\$Rtn:{1} \n..{2}\r\";
+	[ -s $Job-host-{1} ] &&
+		[ \"\$(tail -c 1 $Job-host-{1} |od -iAn |tr -d ' ' )\" != \"10\" ] &&
+		echo -e \"\n\" >> $Job-host-{1};
 	echo \$Rtn >> $Job-host-{1};
 "
-message "####Output####"
-[ ! -t 1 ] || tabs 16
-FailedHosts=()
-HeaderPrinted=NO
-re='^[0-9]+$'
-for ((Cmp=0; Cmp<2; Cmp++))
+[ ! -t 1 ] ||tabs 16
+[ "$Quiet" = "Yes" ] ||message "####Output####"
+set +f
+Nodes=$(cat $Job-nodes |wc -l)
+TailLines=1
+while read C L
 do
-	set +f
-	for F in $Job-host-*
-	do
-		Rtn=$(tail -n 1 $F)
-		if [ -z "$Rtn" ]
-		then
-			let Rtn=1
-		elif [[ $Rtn =~ $re ]]
-		then
-			let Rtn=$Rtn
-		else
-			let Rtn=1
-		fi
-		if [[ ( $Rtn = 0 && $Cmp = 0 ) || ( $Rtn != 0 && $Cmp != 0 ) ]]
-		then
-			if [ "$HeaderPrinted" = "NO" -a $Rtn -eq 0 ]
-			then
-				HeaderPrinted=YES
-				head -n $HeaderLines $F | sed -e "s/^/HeaderLines:\t/"
-				((HeaderLines++))
-			fi
-			Host="$(echo $F | sed -e 's/.*-host-//' )"
-			tail -n +$HeaderLines $F | head -n -1 | sed -e "s/^/$Rtn:$Host:\t/"
-		elif [ $Cmp -eq 0 ]
-		then
-			FailedHosts+=( $( basename $F |cut -d - -f 5-))
-		fi
-	done
-	set -f
+	[ "$C" = "$Nodes" ] ||break
+	((TailLines++))
+	echo "COMMON:$L"
+done < <(for F in $Job-host-*; do head -n -1 $F |nl -ba -w1; done |sort -n |uniq -c |sed -e "s/^ \+//")
+FailedHosts=()
+Succeeded=0
+for F in $Job-host-*
+do
+	Rtn=$(tail -n 1 $F)
+	if [ -z "$Rtn" ]
+	then
+		let Rtn=9
+	elif [[ $Rtn =~ ^[0-9]+$ ]]
+	then
+		let Rtn=$Rtn
+	else
+		let Rtn=9
+	fi
+	if [ $Rtn = 0 ]
+	then
+		((Succeeded++))
+	else
+		FailedHosts+=( $( basename $F |cut -d - -f 5-))
+	fi
+	Host="$(echo $F |sed 's/.*-host-//' )"
+	tail -n +$TailLines $F |head -n -1 |sed "s/^/$Rtn:$Host:\t/"
 done
+set -f
+[ ! -t 1 ] ||tabs 8
 cleanme
-[ ${#FailedHosts[@]} -gt 0 ] && message "\n####Failed hosts: ${#FailedHosts[@]}" && echo "${FailedHosts[*]}"
-[ ! -t 1 ] || tabs 8
+message "####Succeeded: $Succeeded"
+[ ${#FailedHosts[@]} -gt 0 ] && message "####Failed: ${#FailedHosts[@]}" && echo "${FailedHosts[*]}"
 [ ${#FailedHosts[@]} -eq 0 ]
